# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('admission20082009', models.CharField(blank=True, db_column='Admission20082009', null=True, max_length=24)),
                ('admission20092010', models.CharField(blank=True, db_column='Admission20092010', null=True, max_length=14)),
                ('admission20102011', models.CharField(blank=True, db_column='Admission20102011', null=True, max_length=20)),
                ('admission20112012', models.CharField(blank=True, db_column='Admission20112012', null=True, max_length=16)),
                ('admission20122013', models.CharField(blank=True, db_column='Admission20122013', null=True, max_length=10)),
                ('admission20132014', models.CharField(blank=True, db_column='Admission20132014', null=True, max_length=10)),
                ('admission20142015', models.CharField(blank=True, db_column='Admission20142015', null=True, max_length=10)),
                ('admission20152016', models.CharField(blank=True, db_column='Admission20152016', null=True, max_length=10)),
                ('admission20162017', models.CharField(blank=True, db_column='Admission20162017', null=True, max_length=10)),
                ('admission20172018', models.CharField(blank=True, db_column='Admission20172018', null=True, max_length=10)),
                ('admission20182019', models.CharField(blank=True, db_column='Admission20182019', null=True, max_length=10)),
                ('admission20192020', models.CharField(blank=True, db_column='Admission20192020', null=True, max_length=10)),
                ('algant', models.CharField(blank=True, db_column='Algant', null=True, max_length=1)),
                ('algant2', models.CharField(blank=True, db_column='Algant2', null=True, max_length=10)),
                ('algant3', models.CharField(blank=True, db_column='Algant3', null=True, max_length=10)),
                ('algant4', models.CharField(blank=True, db_column='Algant4', null=True, max_length=10)),
                ('algant5', models.CharField(blank=True, db_column='Algant5', null=True, max_length=10)),
                ('année', models.CharField(blank=True, db_column='Année', null=True, max_length=9)),
                ('année2', models.CharField(blank=True, db_column='Année2', null=True, max_length=9)),
                ('année3', models.CharField(blank=True, db_column='Année3', null=True, max_length=9)),
                ('année4', models.CharField(blank=True, db_column='Année4', null=True, max_length=9)),
                ('année5', models.CharField(blank=True, db_column='Année5', null=True, max_length=9)),
                ('anneeentrée', models.CharField(blank=True, db_column='anneeEntrée', null=True, max_length=4)),
                ('anneesortie', models.CharField(blank=True, db_column='anneeSortie', null=True, max_length=4)),
                ('annéevisualisée', models.CharField(blank=True, db_column='annéeVisualisée', null=True, max_length=9)),
                ('avis_2_donné_le', models.CharField(blank=True, db_column='Avis 2 donné le', null=True, max_length=15)),
                ('avis_2_donné_le2', models.CharField(blank=True, db_column='Avis 2 donné le2', null=True, max_length=10)),
                ('avis_2_donné_le3', models.CharField(blank=True, db_column='Avis 2 donné le3', null=True, max_length=10)),
                ('avis_2_donné_le4', models.CharField(blank=True, db_column='Avis 2 donné le4', null=True, max_length=10)),
                ('avis_2_donné_le5', models.CharField(blank=True, db_column='Avis 2 donné le5', null=True, max_length=10)),
                ('avis_2_donné_par', models.CharField(blank=True, db_column='Avis 2 donné par', null=True, max_length=15)),
                ('avis_2_donné_par2', models.CharField(blank=True, db_column='Avis 2 donné par2', null=True, max_length=14)),
                ('avis_2_donné_par3', models.CharField(blank=True, db_column='Avis 2 donné par3', null=True, max_length=14)),
                ('avis_2_donné_par4', models.CharField(blank=True, db_column='Avis 2 donné par4', null=True, max_length=10)),
                ('avis_2_donné_par5', models.CharField(blank=True, db_column='Avis 2 donné par5', null=True, max_length=10)),
                ('avis_donné_le', models.CharField(blank=True, db_column='Avis donné le', null=True, max_length=10)),
                ('avis_donné_le2', models.CharField(blank=True, db_column='Avis donné le2', null=True, max_length=10)),
                ('avis_donné_le3', models.CharField(blank=True, db_column='Avis donné le3', null=True, max_length=10)),
                ('avis_donné_le4', models.CharField(blank=True, db_column='Avis donné le4', null=True, max_length=10)),
                ('avis_donné_le5', models.CharField(blank=True, db_column='Avis donné le5', null=True, max_length=10)),
                ('avis_donné_par', models.CharField(blank=True, db_column='Avis donné par', null=True, max_length=15)),
                ('avis_donné_par2', models.CharField(blank=True, db_column='Avis donné par2', null=True, max_length=15)),
                ('avis_donné_par3', models.CharField(blank=True, db_column='Avis donné par3', null=True, max_length=15)),
                ('avis_donné_par4', models.CharField(blank=True, db_column='Avis donné par4', null=True, max_length=14)),
                ('avis_donné_par5', models.CharField(blank=True, db_column='Avis donné par5', null=True, max_length=14)),
                ('cdpar', models.CharField(blank=True, null=True, max_length=9)),
                ('cdpar2', models.CharField(blank=True, null=True, max_length=10)),
                ('cdpar3', models.CharField(blank=True, null=True, max_length=10)),
                ('cdpar4', models.CharField(blank=True, null=True, max_length=10)),
                ('cdpar5', models.CharField(blank=True, null=True, max_length=10)),
                ('civilité_décompte', models.IntegerField(blank=True, db_column='Civilité Décompte', null=True)),
                ('commentaires20082009', models.CharField(blank=True, null=True, max_length=7)),
                ('commentaires20092010', models.CharField(blank=True, null=True, max_length=10)),
                ('commentaires20102011', models.CharField(blank=True, null=True, max_length=61)),
                ('commentaires20112012', models.CharField(blank=True, null=True, max_length=26)),
                ('commentaires20122013', models.CharField(blank=True, null=True, max_length=15)),
                ('commentaires20132014', models.CharField(blank=True, null=True, max_length=10)),
                ('commentaires20142015', models.CharField(blank=True, null=True, max_length=10)),
                ('commentaires20152016', models.CharField(blank=True, null=True, max_length=10)),
                ('commentaires20162017', models.CharField(blank=True, null=True, max_length=10)),
                ('commentaires20172018', models.CharField(blank=True, null=True, max_length=10)),
                ('commentaires20182019', models.CharField(blank=True, null=True, max_length=10)),
                ('commentaires20192020', models.CharField(blank=True, null=True, max_length=10)),
                ('complément_de_dossier_demandé_le', models.CharField(blank=True, db_column='Complément de dossier demandé le', null=True, max_length=10)),
                ('complément_de_dossier_demandé_le2', models.CharField(blank=True, db_column='Complément de dossier demandé le2', null=True, max_length=10)),
                ('complément_de_dossier_demandé_le3', models.CharField(blank=True, db_column='Complément de dossier demandé le3', null=True, max_length=10)),
                ('complément_de_dossier_demandé_le4', models.CharField(blank=True, db_column='Complément de dossier demandé le4', null=True, max_length=10)),
                ('complément_de_dossier_demandé_le5', models.CharField(blank=True, db_column='Complément de dossier demandé le5', null=True, max_length=10)),
                ('confirmation', models.CharField(blank=True, db_column='Confirmation', null=True, max_length=22)),
                ('confirmation_décompte', models.IntegerField(blank=True, db_column='Confirmation Décompte', null=True)),
                ('confirmation_décompte_cumulé', models.IntegerField(blank=True, db_column='Confirmation Décompte cumulé', null=True)),
                ('confirmation2', models.CharField(blank=True, db_column='Confirmation2', null=True, max_length=16)),
                ('confirmation3', models.CharField(blank=True, db_column='Confirmation3', null=True, max_length=11)),
                ('confirmation4', models.CharField(blank=True, db_column='Confirmation4', null=True, max_length=7)),
                ('confirmation5', models.CharField(blank=True, db_column='Confirmation5', null=True, max_length=6)),
                ('date_d_arrivée_du_dossier', models.CharField(blank=True, db_column="Date d'arrivée du dossier", null=True, max_length=20)),
                ('date_d_arrivée_du_dossier2', models.CharField(blank=True, db_column="Date d'arrivée du dossier2", null=True, max_length=10)),
                ('date_d_arrivée_du_dossier3', models.CharField(blank=True, db_column="Date d'arrivée du dossier3", null=True, max_length=10)),
                ('date_d_arrivée_du_dossier4', models.CharField(blank=True, db_column="Date d'arrivée du dossier4", null=True, max_length=10)),
                ('date_d_arrivée_du_dossier5', models.CharField(blank=True, db_column="Date d'arrivée du dossier5", null=True, max_length=10)),
                ('durée', models.CharField(blank=True, null=True, max_length=8)),
                ('durée20002010', models.CharField(blank=True, null=True, max_length=8)),
                ('durée20082009', models.CharField(blank=True, null=True, max_length=8)),
                ('email', models.CharField(blank=True, null=True, max_length=34)),
                ('email2', models.CharField(blank=True, null=True, max_length=36)),
                ('entré_en', models.CharField(blank=True, db_column='entré en', null=True, max_length=8)),
                ('erasmus', models.CharField(blank=True, db_column='Erasmus', null=True, max_length=1)),
                ('erasmus2', models.CharField(blank=True, db_column='Erasmus2', null=True, max_length=10)),
                ('erasmus3', models.CharField(blank=True, db_column='Erasmus3', null=True, max_length=10)),
                ('erasmus4', models.CharField(blank=True, db_column='Erasmus4', null=True, max_length=10)),
                ('erasmus5', models.CharField(blank=True, db_column='Erasmus5', null=True, max_length=10)),
                ('fmjh', models.CharField(blank=True, db_column='FMJH', null=True, max_length=1)),
                ('fmjh2', models.CharField(blank=True, db_column='FMJH2', null=True, max_length=10)),
                ('fmjh3', models.CharField(blank=True, db_column='FMJH3', null=True, max_length=10)),
                ('fmjh4', models.CharField(blank=True, db_column='FMJH4', null=True, max_length=10)),
                ('fmjh5', models.CharField(blank=True, db_column='FMJH5', null=True, max_length=10)),
                ('formation20082009', models.CharField(blank=True, db_column='Formation20082009', null=True, max_length=60)),
                ('formation20092010', models.CharField(blank=True, db_column='Formation20092010', null=True, max_length=69)),
                ('formation20102011', models.CharField(blank=True, db_column='Formation20102011', null=True, max_length=69)),
                ('formation20112012', models.CharField(blank=True, db_column='Formation20112012', null=True, max_length=88)),
                ('formation20122013', models.CharField(blank=True, db_column='Formation20122013', null=True, max_length=57)),
                ('formation20132014', models.CharField(blank=True, db_column='Formation20132014', null=True, max_length=55)),
                ('formation20142015', models.CharField(blank=True, db_column='Formation20142015', null=True, max_length=32)),
                ('formation20152016', models.CharField(blank=True, db_column='Formation20152016', null=True, max_length=10)),
                ('formation20162017', models.CharField(blank=True, db_column='Formation20162017', null=True, max_length=10)),
                ('formation20172018', models.CharField(blank=True, db_column='Formation20172018', null=True, max_length=10)),
                ('formation20182019', models.CharField(blank=True, db_column='Formation20182019', null=True, max_length=10)),
                ('formation20192020', models.CharField(blank=True, db_column='Formation20192020', null=True, max_length=10)),
                ('genre', models.CharField(blank=True, db_column='Genre', null=True, max_length=3)),
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('l3_ecom', models.CharField(blank=True, db_column='L3 ECOM', null=True, max_length=3)),
                ('l3_ecom2', models.CharField(blank=True, db_column='L3 ECOM2', null=True, max_length=3)),
                ('l3_ecom3', models.CharField(blank=True, db_column='L3 ECOM3', null=True, max_length=10)),
                ('l3_ecom4', models.CharField(blank=True, db_column='L3 ECOM4', null=True, max_length=10)),
                ('l3_ecom5', models.CharField(blank=True, db_column='L3 ECOM5', null=True, max_length=10)),
                ('l3_map', models.CharField(blank=True, db_column='L3 MAP', null=True, max_length=12)),
                ('l3_map2', models.CharField(blank=True, db_column='L3 MAP2', null=True, max_length=12)),
                ('l3_map3', models.CharField(blank=True, db_column='L3 MAP3', null=True, max_length=3)),
                ('l3_map4', models.CharField(blank=True, db_column='L3 MAP4', null=True, max_length=3)),
                ('l3_map5', models.CharField(blank=True, db_column='L3 MAP5', null=True, max_length=3)),
                ('l3_mathens', models.CharField(blank=True, db_column='L3 MATHENS', null=True, max_length=3)),
                ('l3_mathens2', models.CharField(blank=True, db_column='L3 MATHENS2', null=True, max_length=3)),
                ('l3_mathens3', models.CharField(blank=True, db_column='L3 MATHENS3', null=True, max_length=3)),
                ('l3_mathens4', models.CharField(blank=True, db_column='L3 MATHENS4', null=True, max_length=10)),
                ('l3_mathens5', models.CharField(blank=True, db_column='L3 MATHENS5', null=True, max_length=10)),
                ('l3_mathinfo', models.CharField(blank=True, db_column='L3 MATHINFO', null=True, max_length=12)),
                ('l3_mathinfo2', models.CharField(blank=True, db_column='L3 MATHINFO2', null=True, max_length=3)),
                ('l3_mathinfo3', models.CharField(blank=True, db_column='L3 MATHINFO3', null=True, max_length=3)),
                ('l3_mathinfo4', models.CharField(blank=True, db_column='L3 MATHINFO4', null=True, max_length=10)),
                ('l3_mathinfo5', models.CharField(blank=True, db_column='L3 MATHINFO5', null=True, max_length=10)),
                ('l3_mfa', models.CharField(blank=True, db_column='L3 MFA', null=True, max_length=3)),
                ('l3_mfa2', models.CharField(blank=True, db_column='L3 MFA2', null=True, max_length=3)),
                ('l3_mfa3', models.CharField(blank=True, db_column='L3 MFA3', null=True, max_length=3)),
                ('l3_mfa4', models.CharField(blank=True, db_column='L3 MFA4', null=True, max_length=10)),
                ('l3_mfa5', models.CharField(blank=True, db_column='L3 MFA5', null=True, max_length=10)),
                ('l3_mint1', models.CharField(blank=True, db_column='L3 MINT1', null=True, max_length=3)),
                ('l3_mint2', models.CharField(blank=True, db_column='L3 MINT2', null=True, max_length=3)),
                ('l3_mint3', models.CharField(blank=True, db_column='L3 MINT3', null=True, max_length=3)),
                ('l3_mint4', models.CharField(blank=True, db_column='L3 MINT4', null=True, max_length=3)),
                ('l3_mint5', models.CharField(blank=True, db_column='L3 MINT5', null=True, max_length=10)),
                ('l3mfaingé', models.CharField(blank=True, db_column='L3MFAIngé', null=True, max_length=3)),
                ('l3mfaingé2', models.CharField(blank=True, db_column='L3MFAIngé2', null=True, max_length=3)),
                ('l3mfaingé3', models.CharField(blank=True, db_column='L3MFAIngé3', null=True, max_length=10)),
                ('l3mfaingé4', models.CharField(blank=True, db_column='L3MFAIngé4', null=True, max_length=10)),
                ('l3mfaingé5', models.CharField(blank=True, db_column='L3MFAIngé5', null=True, max_length=10)),
                ('m1_mfa', models.CharField(blank=True, db_column='M1 MFA', null=True, max_length=3)),
                ('m1_mfa2', models.CharField(blank=True, db_column='M1 MFA2', null=True, max_length=3)),
                ('m1_mfa3', models.CharField(blank=True, db_column='M1 MFA3', null=True, max_length=3)),
                ('m1_mfa4', models.CharField(blank=True, db_column='M1 MFA4', null=True, max_length=3)),
                ('m1_mfa5', models.CharField(blank=True, db_column='M1 MFA5', null=True, max_length=10)),
                ('m1mfaingé', models.CharField(blank=True, db_column='M1MFAIngé', null=True, max_length=3)),
                ('m1mfaingé2', models.CharField(blank=True, db_column='M1MFAIngé2', null=True, max_length=3)),
                ('m1mfaingé3', models.CharField(blank=True, db_column='M1MFAIngé3', null=True, max_length=10)),
                ('m1mfaingé4', models.CharField(blank=True, db_column='M1MFAIngé4', null=True, max_length=10)),
                ('m1mfaingé5', models.CharField(blank=True, db_column='M1MFAIngé5', null=True, max_length=10)),
                ('magistère_1', models.CharField(blank=True, db_column='Magistère 1', null=True, max_length=3)),
                ('magistère_12', models.CharField(blank=True, db_column='Magistère 12', null=True, max_length=3)),
                ('magistère_13', models.CharField(blank=True, db_column='Magistère 13', null=True, max_length=10)),
                ('magistère_14', models.CharField(blank=True, db_column='Magistère 14', null=True, max_length=10)),
                ('magistère_15', models.CharField(blank=True, db_column='Magistère 15', null=True, max_length=10)),
                ('magistère_2', models.CharField(blank=True, db_column='Magistère 2', null=True, max_length=3)),
                ('magistère_22', models.CharField(blank=True, db_column='Magistère 22', null=True, max_length=3)),
                ('magistère_23', models.CharField(blank=True, db_column='Magistère 23', null=True, max_length=10)),
                ('magistère_24', models.CharField(blank=True, db_column='Magistère 24', null=True, max_length=10)),
                ('magistère_25', models.CharField(blank=True, db_column='Magistère 25', null=True, max_length=10)),
                ('magistère_3', models.CharField(blank=True, db_column='Magistère 3', null=True, max_length=3)),
                ('magistère_32', models.CharField(blank=True, db_column='Magistère 32', null=True, max_length=10)),
                ('magistère_33', models.CharField(blank=True, db_column='Magistère 33', null=True, max_length=3)),
                ('magistère_34', models.CharField(blank=True, db_column='Magistère 34', null=True, max_length=10)),
                ('magistère_35', models.CharField(blank=True, db_column='Magistère 35', null=True, max_length=10)),
                ('nom', models.CharField(blank=True, db_column='Nom', null=True, max_length=25)),
                ('numero_etudiant', models.CharField(blank=True, db_column='Numero Etudiant', null=True, max_length=10)),
                ('numero_opi', models.CharField(blank=True, db_column='Numero OPI', null=True, max_length=22)),
                ('numero_opi2', models.CharField(blank=True, db_column='Numero OPI2', null=True, max_length=11)),
                ('numero_opi3', models.CharField(blank=True, db_column='Numero OPI3', null=True, max_length=5)),
                ('numero_opi4', models.CharField(blank=True, db_column='Numero OPI4', null=True, max_length=3)),
                ('numero_opi5', models.CharField(blank=True, db_column='Numero OPI5', null=True, max_length=3)),
                ('origine', models.CharField(blank=True, db_column='Origine', null=True, max_length=41)),
                ('origine2', models.CharField(blank=True, db_column='Origine2', null=True, max_length=18)),
                ('origine3', models.CharField(blank=True, db_column='Origine3', null=True, max_length=17)),
                ('origine4', models.CharField(blank=True, db_column='Origine4', null=True, max_length=12)),
                ('origine5', models.CharField(blank=True, db_column='Origine5', null=True, max_length=10)),
                ('parcours_demandé', models.CharField(blank=True, db_column='Parcours demandé', null=True, max_length=41)),
                ('parcours_demandé2', models.CharField(blank=True, db_column='Parcours demandé2', null=True, max_length=25)),
                ('parcours_demandé3', models.CharField(blank=True, db_column='Parcours demandé3', null=True, max_length=14)),
                ('parcours_demandé4', models.CharField(blank=True, db_column='Parcours demandé4', null=True, max_length=14)),
                ('parcours_demandé5', models.CharField(blank=True, db_column='Parcours demandé5', null=True, max_length=6)),
                ('prénom', models.CharField(blank=True, db_column='Prénom', null=True, max_length=28)),
                ('remarques', models.CharField(blank=True, db_column='Remarques', null=True, max_length=88)),
                ('remarques2', models.CharField(blank=True, db_column='Remarques2', null=True, max_length=41)),
                ('remarques3', models.CharField(blank=True, db_column='Remarques3', null=True, max_length=10)),
                ('remarques4', models.CharField(blank=True, db_column='Remarques4', null=True, max_length=9)),
                ('remarques5', models.CharField(blank=True, db_column='Remarques5', null=True, max_length=10)),
                ('remarquesc', models.CharField(blank=True, db_column='RemarquesC', null=True, max_length=52)),
                ('réponse', models.CharField(blank=True, db_column='Réponse', null=True, max_length=48)),
                ('réponse2', models.CharField(blank=True, db_column='Réponse2', null=True, max_length=29)),
                ('réponse3', models.CharField(blank=True, db_column='Réponse3', null=True, max_length=11)),
                ('réponse4', models.CharField(blank=True, db_column='Réponse4', null=True, max_length=7)),
                ('réponse5', models.CharField(blank=True, db_column='Réponse5', null=True, max_length=6)),
                ('résultat20082009', models.CharField(blank=True, db_column='Résultat20082009', null=True, max_length=10)),
                ('résultat20092010', models.CharField(blank=True, db_column='Résultat20092010', null=True, max_length=10)),
                ('résultat20102011', models.CharField(blank=True, db_column='Résultat20102011', null=True, max_length=10)),
                ('résultat20112012', models.CharField(blank=True, db_column='Résultat20112012', null=True, max_length=10)),
                ('résultat20122013', models.CharField(blank=True, db_column='Résultat20122013', null=True, max_length=10)),
                ('résultat20132014', models.CharField(blank=True, db_column='Résultat20132014', null=True, max_length=10)),
                ('résultat20142015', models.CharField(blank=True, db_column='Résultat20142015', null=True, max_length=10)),
                ('résultat20152016', models.CharField(blank=True, db_column='Résultat20152016', null=True, max_length=10)),
                ('résultat20162017', models.CharField(blank=True, db_column='Résultat20162017', null=True, max_length=10)),
                ('résultat20172018', models.CharField(blank=True, db_column='Résultat20172018', null=True, max_length=10)),
                ('résultat20182019', models.CharField(blank=True, db_column='Résultat20182019', null=True, max_length=10)),
                ('résultat20192020', models.CharField(blank=True, db_column='Résultat20192020', null=True, max_length=10)),
                ('rien', models.CharField(blank=True, null=True, max_length=10)),
                ('rubrique', models.CharField(blank=True, db_column='Rubrique', null=True, max_length=10)),
                ('rubrique_245', models.CharField(blank=True, db_column='Rubrique 245', null=True, max_length=10)),
                ('saisie_opi_le', models.CharField(blank=True, db_column='Saisie OPI le', null=True, max_length=10)),
                ('saisie_opi_le2', models.CharField(blank=True, db_column='Saisie OPI le2', null=True, max_length=9)),
                ('saisie_opi_le3', models.CharField(blank=True, db_column='Saisie OPI le3', null=True, max_length=10)),
                ('saisie_opi_le4', models.CharField(blank=True, db_column='Saisie OPI le4', null=True, max_length=10)),
                ('saisie_opi_le5', models.CharField(blank=True, db_column='Saisie OPI le5', null=True, max_length=10)),
                ('sorti_en', models.CharField(blank=True, db_column='Sorti en', null=True, max_length=9)),
                ('vérifié_le', models.CharField(blank=True, db_column='Vérifié le', null=True, max_length=10)),
            ],
            options={
                'db_table': 'candidature',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='candidat',
        ),
    ]
